mugiwara = list()
mugiwara.append('brook')
mugiwara.append('jimbe')
mugiwara.append('robin')
mugiwara.append('nami')
mugiwara.append('choppa')
mugiwara.append('sanji')
mugiwara.append('usopp')
mugiwara.append('franky')
mugiwara.append('zoro')
mugiwara.append('luffy')
mugiwara.append('yamato')
print(mugiwara)

print('yamato' in mugiwara)
print('utaha' in mugiwara)
print('lucci' not in mugiwara)

mugiwara.sort()
print(mugiwara)